<?php
$db_table_composition="composition";
$db_table_ingredients="ingredients";
$db_table_names="names";
$db_table_users="users";
$db_table_comments="comments";

$db_field_cocktail_eval="cocktail_eval";
$db_field_cocktail_name="cocktail_name";
$db_field_cocktail_id="cocktail_id";
$db_field_comment="cocktail_comment";
$db_field_image="cocktail_image";
$db_field_user_id="user_id";
$db_field_user_name="user_name";
$db_field_user_password="user_password";
$db_field_ingredient_id="ingredient_id";
$db_field_ingredient_name="ingredient_name";
$db_field_ingredient_proportion="ingredient_proportion";
$db_field_composition_order="composition_order";
$db_field_comment_date="comment_date";
$db_field_comment_nickname="comment_nickname";
$db_field_comment_text="comment_text";
$db_field_comment_id="comment_id";
?>